apiVersion: v1
kind: Service
metadata:
  name: brilliant-api
  namespace: brilliant
spec:
  selector:
    app: brilliant-api
  ports:
    - name: http
      port: 3000
      targetPort: 3000
  type: ClusterIP
