apiVersion: v1
kind: Service
metadata:
  name: brilliant-web
  namespace: brilliant
spec:
  selector:
    app: brilliant-web
  ports:
    - name: http
      port: 80
      targetPort: 80
  type: ClusterIP
